name: todolist
description: A new Flutter project.


publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_native_splash: ^2.0.5
  faker: ^2.0.0
  provider: ^5.0.0


flutter_native_splash:
  color: "#c0d6e4"
  image: assets/splashscreen/icon.png


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 200
